### ISSUE TITLE
java1.8 run error

### ISSUE THREAD

**Issue by icyboxs** [Scrappers-glitch/SS-Editor#21]
```
信息: Unlocked
Exception in thread "GL-Renderer" java.lang.UnsatisfiedLinkError: The required native library 'jinput-dx8_64' was not found in the classpath via 'native/windows/jinput-dx8_64.dll'. Error message: no jinput-dx8_64 in java.library.path
	at com.jme3.system.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java:589)
	at com.ss.editor.Editor.start(Editor.java:167)
	at java.lang.Thread.run(Thread.java:750)
INFO 11:39:42:777 ExecutorManager: initialized.
INFO 11:39:42:885 ClassPathScanner: scanning E:\Gradle\caches\modules-2\files-2.1\org.jmonkeyengine\jme3-effects\3.5.1-stable\2124d7ba6393ef557add3d8ed33642a7073f5ea\jme3-effects-3.5.1-stable.jar
INFO 11:39:42:921 ClassPathScanner: scanning E:\Gradle\caches\modules-2\files-2.1\org.jmonkeyengine\jme3-core\3.5.1-stable\eea5ce6e43f452414e23ea3664d0a01ce5a57b36\jme3-core-3.5.1-stable.jar
INFO 11:39:43:078 ClassPathScanner: scanning E:\Gradle\caches\modules-2\files-2.1\org.jmonkeyengine\jme3-effects\3.5.1-stable\2124d7ba6393ef557add3d8ed33642a7073f5ea\jme3-effects-3.5.1-stable.jar
INFO 11:39:43:089 ClassPathScanner: scanning E:\Gradle\caches\modules-2\files-2.1\org.jmonkeyengine\jme3-core\3.5.1-stable\eea5ce6e43f452414e23ea3664d0a01ce5a57b36\jme3-core-3.5.1-stable.jar
INFO 11:39:43:286 ClassPathScanner: scanned for 899 classes and 227 resources.
INFO 11:39:43:286 ClassPathScanner: scanned for 899 classes and 227 resources.
Exception in Application start method
WARNING 11:39:43:288 InitializeManager: java.lang.NullPointerException
	at com.ss.editor.manager.ResourceManager.<init>(ResourceManager.java:187)
	at com.ss.editor.manager.ResourceManager.getInstance(ResourceManager.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ss.rlib.manager.InitializeManager.initialize(InitializeManager.java:41)
	at com.ss.editor.thread.InitializationThread.run(InitializationThread.java:16)

Exception in thread "JFX-MainApplication" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ExceptionInInitializerError
	at com.ss.editor.ui.component.creator.FileCreatorRegistry.<init>(FileCreatorRegistry.java:50)
	at com.ss.editor.ui.component.creator.FileCreatorRegistry.<clinit>(FileCreatorRegistry.java:27)
	at com.ss.editor.ui.component.editor.area.EditorAreaComponent.<clinit>(EditorAreaComponent.java:81)
	at com.ss.editor.ui.builder.EditorFXSceneBuilder.build(EditorFXSceneBuilder.java:105)
	at com.ss.editor.ui.builder.EditorFXSceneBuilder.build(EditorFXSceneBuilder.java:89)
	at com.ss.editor.JFXApplication.buildScene(JFXApplication.java:132)
	at com.ss.editor.JFXApplication.start(JFXApplication.java:83)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	... 1 more
Caused by: java.lang.NullPointerException
	at com.ss.editor.manager.ResourceManager.<init>(ResourceManager.java:187)
	at com.ss.editor.manager.ResourceManager.getInstance(ResourceManager.java:95)
	at com.ss.editor.ui.component.creator.impl.material.MaterialFileCreator.<clinit>(MaterialFileCreator.java:40)
	... 16 more
```
build.gradle file
```
plugins {
    id 'java'

}
String engineVersion = "3.5.1-stable"
group 'org.scrappers'
version '1.0-RM-VERSION'

repositories {
    mavenCentral()
    maven { url 'https://jcenter.bintray.com' } // for SimMath
}
apply plugin: 'java'
sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    implementation 'org.jetbrains:annotations:16.0.2'
    /* local dependencies */
    implementation fileTree(dir: "libs", include: ["*.jar", "*.so"])
    implementation fileTree(dir: "libs/extensions", include: ["*.jar", "*.so"])
    implementation fileTree(dir: "libs/extensions/simsilica", include: ["*.jar", "*.so"])
    implementation fileTree(dir: "libs/extensions/toneg0d", include: ["*.jar", "*.so"])
    implementation fileTree(dir: "libs/extensions/xbuf", include: ["*.jar", "*.so"])
    implementation fileTree(dir: "libs/http", include: ["*.jar", "*.so"])
    implementation fileTree(dir: "libs/svg", include: ["*.jar", "*.so"])

    /* remote dependencies */
    implementation "org.jmonkeyengine:jme3-core:$engineVersion"
    implementation "org.jmonkeyengine:jme3-desktop:$engineVersion"
    implementation "org.jmonkeyengine:jme3-effects:$engineVersion"
    implementation "org.jmonkeyengine:jme3-terrain:$engineVersion"
    implementation "org.jmonkeyengine:jme3-lwjgl3:$engineVersion"
    implementation "org.jmonkeyengine:jme3-plugins:$engineVersion"

}

test {
    useJUnitPlatform()
}
```
I searched Google for the answer but couldn't find it
Ask questions about this problem

**Comment by pavly-gerges** [comment]
Hello, have you managed to find an answer ?
