### ISSUE TITLE
Memory leak when saving the terrain

### ISSUE THREAD

**Issue by pavly-gerges** [Scrappers-glitch/SS-Editor#3]
```
java.lang.NullPointerException
	at com.jme3.scene.Geometry.updateModelBound(Geometry.java:280)
	at com.jme3.scene.Node.updateModelBound(Node.java:768)
	at com.jme3.scene.Node.updateModelBound(Node.java:768)
	at com.jme3.scene.Node.updateModelBound(Node.java:768)
	at com.ss.editor.util.GeomUtils.getCollisionFromScreenPos(GeomUtils.java:295)
	at com.ss.editor.util.GeomUtils.getContactPointFromScreenPos(GeomUtils.java:234)
	at com.ss.editor.util.GeomUtils.getContactPointFromCursor(GeomUtils.java:220)
	at com.ss.editor.state.editor.impl.scene.AbstractSceneEditorAppState.updateEditingNodes(AbstractSceneEditorAppState.java:808)
	at com.ss.editor.state.editor.impl.scene.AbstractSceneEditorAppState.update(AbstractSceneEditorAppState.java:722)
	at com.ss.editor.state.editor.impl.model.ModelEditorAppState.update(ModelEditorAppState.java:158)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:287)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236)
	at com.jme3x.jfx.injfx.JmeToJFXApplication.update(JmeToJFXApplication.java:24)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pavly-gerges** [comment]
```
java.lang.NullPointerException
	at com.jme3.renderer.opengl.GLRenderer.renderMesh(GLRenderer.java:2824)
	at com.jme3.material.logic.DefaultTechniqueDefLogic.renderMeshFromGeometry(DefaultTechniqueDefLogic.java:70)
	at com.jme3.material.logic.SinglePassLightingLogic.render(SinglePassLightingLogic.java:216)
	at com.jme3.material.Technique.render(Technique.java:166)
	at com.jme3.material.Material.render(Material.java:970)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:877)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:779)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1108)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
	at com.jme3x.jfx.injfx.JmeToJFXApplication.update(JmeToJFXApplication.java:24)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pavly-gerges** [comment]
Something is wrong in the terrain generator that appears to be creating null boundary meshes....that is reflected during the next update or something is wrong with the save.

**Comment by pavly-gerges** [comment]
This appears to be due to terrain brush creating null meshes that interrogate with jme update....
