### ISSUE TITLE
Scene graph update issue when saving the terrain editor 

### ISSUE THREAD

**Issue by pavly-gerges** [Scrappers-glitch/SS-Editor#4]
```
java.lang.IllegalStateException: Scene graph is not properly updated for rendering.
State was changed after rootNode.updateGeometricState() call. 
Make sure you do not modify the scene from another thread!
Problem spatial name: ModelNode
	at com.jme3.scene.Spatial.checkCulling(Spatial.java:421)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:717)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
	at com.jme3x.jfx.injfx.JmeToJFXApplication.update(JmeToJFXApplication.java:24)
	at com.ss.editor.Editor.update(Editor.java:308)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pavly-gerges** [comment]
This issue has been fixed by using `EditorStateManager.State` instead of StampLockers to keep jme3 scene updater synchronized with the editor state PR #8 and it's a duplicate of issue #3 .
